export const distritos = [
  'Açores', 'Aveiro', 'Beja', 'Braga', 'Bragança', 'Castelo Branco', 'Coimbra', 'Évora',
  'Faro', 'Guarda', 'Leiria', 'Lisboa', 'Madeira', 'Portalegre', 'Porto', 'Santarém',
  'Setúbal', 'Viana do Castelo', 'Vila Real', 'Viseu',
];

export const concelhosPorDistrito = {
  'Açores': ['Angra do Heroísmo', 'Calheta (São Jorge)', 'Corvo', 'Horta', 'Lagoa', 'Lajes das Flores', 'Lajes do Pico', 'Madalena', 'Nordeste', 'Ponta Delgada', 'Povoação', 'Praia da Vitória', 'Ribeira Grande', 'Santa Cruz da Graciosa', 'Santa Cruz das Flores', 'São Roque do Pico', 'Velas', 'Vila do Porto', 'Vila Franca do Campo'],
  'Aveiro': ['Águeda', 'Albergaria-a-Velha', 'Anadia', 'Arouca', 'Aveiro', 'Castelo de Paiva', 'Espinho', 'Estarreja', 'Santa Maria da Feira', 'Ílhavo', 'Mealhada', 'Murtosa', 'Oliveira de Azeméis', 'Oliveira do Bairro', 'Ovar', 'São João da Madeira', 'Sever do Vouga', 'Vagos', 'Vale de Cambra'],
  'Beja': ['Aljustrel', 'Almodôvar', 'Alvito', 'Barrancos', 'Beja', 'Castro Verde', 'Cuba', 'Ferreira do Alentejo', 'Mértola', 'Moura', 'Odemira', 'Ourique', 'Serpa', 'Vidigueira'],
  'Braga': ['Amares', 'Barcelos', 'Braga', 'Cabeceiras de Basto', 'Celorico de Basto', 'Esposende', 'Fafe', 'Guimarães', 'Póvoa de Lanhoso', 'Terras de Bouro', 'Vieira do Minho', 'Vila Nova de Famalicão', 'Vila Verde', 'Vizela'],
  'Bragança': ['Alfândega da Fé', 'Bragança', 'Carrazeda de Ansiães', 'Freixo de Espada à Cinta', 'Macedo de Cavaleiros', 'Miranda do Douro', 'Mirandela', 'Mogadouro', 'Torre de Moncorvo', 'Vila Flor', 'Vimioso', 'Vinhais'],
  'Castelo Branco': ['Belmonte', 'Castelo Branco', 'Covilhã', 'Fundão', 'Idanha-a-Nova', 'Oleiros', 'Penamacor', 'Proença-a-Nova', 'Sertã', 'Vila de Rei', 'Vila Velha de Ródão'],
  'Coimbra': ['Arganil', 'Cantanhede', 'Coimbra', 'Condeixa-a-Nova', 'Figueira da Foz', 'Góis', 'Lousã', 'Mira', 'Miranda do Corvo', 'Montemor-o-Velho', 'Oliveira do Hospital', 'Pampilhosa da Serra', 'Penacova', 'Penela', 'Soure', 'Tábua', 'Vila Nova de Poiares'],
  'Évora': ['Alandroal', 'Arraiolos', 'Borba', 'Estremoz', 'Évora', 'Montemor-o-Novo', 'Mora', 'Mourão', 'Portel', 'Redondo', 'Reguengos de Monsaraz', 'Vendas Novas', 'Viana do Alentejo', 'Vila Viçosa'],
  'Faro': ['Albufeira', 'Alcoutim', 'Aljezur', 'Castro Marim', 'Faro', 'Lagoa', 'Lagos', 'Loulé', 'Monchique', 'Olhão', 'Portimão', 'São Brás de Alportel', 'Silves', 'Tavira', 'Vila do Bispo', 'Vila Real de Santo António'],
  'Guarda': ['Aguiar da Beira', 'Almeida', 'Celorico da Beira', 'Figueira de Castelo Rodrigo', 'Fornos de Algodres', 'Gouveia', 'Guarda', 'Manteigas', 'Mêda', 'Pinhel', 'Sabugal', 'Seia', 'Trancoso', 'Vila Nova de Foz Côa'],
  'Leiria': ['Alcobaça', 'Alvaiázere', 'Ansião', 'Batalha', 'Bombarral', 'Caldas da Rainha', 'Castanheira de Pêra', 'Figueiró dos Vinhos', 'Leiria', 'Marinha Grande', 'Nazaré', 'Óbidos', 'Pedrógão Grande', 'Peniche', 'Pombal', 'Porto de Mós'],
  'Lisboa': ['Alenquer', 'Amadora', 'Arruda dos Vinhos', 'Azambuja', 'Cadaval', 'Cascais', 'Lisboa', 'Loures', 'Lourinhã', 'Mafra', 'Odivelas', 'Oeiras', 'Sintra', 'Sobral de Monte Agraço', 'Torres Vedras', 'Vila Franca de Xira'],
  'Madeira': ['Calheta (Madeira)', 'Câmara de Lobos', 'Funchal', 'Machico', 'Ponta do Sol', 'Porto Moniz', 'Porto Santo', 'Ribeira Brava', 'Santa Cruz', 'Santana', 'São Vicente'],
  'Portalegre': ['Alter do Chão', 'Arronches', 'Avis', 'Campo Maior', 'Castelo de Vide', 'Crato', 'Elvas', 'Fronteira', 'Gavião', 'Marvão', 'Monforte', 'Nisa', 'Ponte de Sor', 'Portalegre', 'Sousel'],
  'Porto': ['Amarante', 'Baião', 'Felgueiras', 'Gondomar', 'Lousada', 'Maia', 'Marco de Canaveses', 'Matosinhos', 'Paços de Ferreira', 'Paredes', 'Penafiel', 'Porto', 'Póvoa de Varzim', 'Santo Tirso', 'Trofa', 'Valongo', 'Vila do Conde', 'Vila Nova de Gaia'],
  'Santarém': ['Abrantes', 'Alcanena', 'Almeirim', 'Alpiarça', 'Benavente', 'Cartaxo', 'Chamusca', 'Constância', 'Coruche', 'Entroncamento', 'Ferreira do Zêzere', 'Golegã', 'Mação', 'Ourém', 'Rio Maior', 'Salvaterra de Magos', 'Santarém', 'Sardoal', 'Tomar', 'Torres Novas', 'Vila Nova da Barquinha'],
  'Setúbal': ['Alcácer do Sal', 'Alcochete', 'Almada', 'Barreiro', 'Grândola', 'Moita', 'Montijo', 'Palmela', 'Santiago do Cacém', 'Seixal', 'Sesimbra', 'Setúbal', 'Sines'],
  'Viana do Castelo': ['Arcos de Valdevez', 'Caminha', 'Melgaço', 'Monção', 'Paredes de Coura', 'Ponte da Barca', 'Ponte de Lima', 'Valença', 'Viana do Castelo', 'Vila Nova de Cerveira'],
  'Vila Real': ['Alijó', 'Boticas', 'Chaves', 'Mesão Frio', 'Mondim de Basto', 'Montalegre', 'Murça', 'Peso da Régua', 'Ribeira de Pena', 'Sabrosa', 'Santa Marta de Penaguião', 'Valpaços', 'Vila Pouca de Aguiar', 'Vila Real'],
  'Viseu': ['Armamar', 'Carregal do Sal', 'Castro Daire', 'Cinfães', 'Lamego', 'Mangualde', 'Moimenta da Beira', 'Mortágua', 'Nelas', 'Oliveira de Frades', 'Penalva do Castelo', 'Penedono', 'Resende', 'Santa Comba Dão', 'São João da Pesqueira', 'São Pedro do Sul', 'Sátão', 'Sernancelhe', 'Tabuaço', 'Tarouca', 'Tondela', 'Vila Nova de Paiva', 'Viseu', 'Vouzela'],
};

// Nota: cobre os concelhos mais populosos com as freguesias mais conhecidas — não é
// uma lista exaustiva de todas as freguesias de Portugal (seriam milhares de entradas).
// Nos concelhos sem lista própria, a pesquisa fica pelo concelho (nível acima).
export const freguesiasPorConcelho = {
  'Lisboa': [
    'Alvalade', 'Areeiro', 'Arroios', 'Avenidas Novas', 'Belém', 'Benfica',
    'Campo de Ourique', 'Campolide', 'Carnide', 'Estrela', 'Marvila', 'Parque das Nações',
    'Santa Maria Maior', 'Santo António', 'São Domingos de Benfica', 'São Vicente',
  ],
  'Porto': ['Bonfim', 'Campanhã', 'Cedofeita', 'Lordelo do Ouro e Massarelos', 'Paranhos', 'Ramalde'],
  'Cascais': ['Cascais e Estoril', 'Alcabideche', 'Carcavelos e Parede', 'São Domingos de Rana'],
  'Sintra': ['Sintra', 'Queluz e Belas', 'Agualva e Mira-Sintra', 'Rio de Mouro', 'Algueirão-Mem Martins'],
  'Braga': ['São Vicente', 'São José de São Lázaro', 'Maximinos', 'Real'],
  'Faro': ['Faro (Sé e São Pedro)', 'Montenegro'],
  'Coimbra': ['Sé Nova', 'Santo António dos Olivais', 'Santa Clara'],
  'Vila Nova de Gaia': ['Santa Marinha e São Pedro da Afurada', 'Mafamude e Vilar do Paraíso', 'Canidelo'],
  'Setúbal': ['Setúbal (São Julião, Nossa Senhora da Anunciada e Santa Maria da Graça)'],
  'Matosinhos': ['Matosinhos e Leça da Palmeira', 'Perafita, Lavra e Santa Cruz do Bispo'],
  'Guimarães': ['Azurém', 'Creixomil', 'Fermentões', 'Oliveira, São Paio e São Sebastião', 'Urgezes'],
  'Barcelos': ['Barcelos', 'Barcelinhos', 'Arcozelo', 'Abade de Neiva'],
  'Vila Nova de Famalicão': ['Antas e Abade de Vermoim', 'Calendário', 'Gavião', 'Ribeirão'],
  'Aveiro': ['Glória e Vera Cruz', 'São Bernardo', 'Santa Joana', 'Esgueira', 'Cacia'],
  'Leiria': ['Leiria, Pousos, Barreira e Cortes', 'Marrazes e Barosa', 'Parceiros e Azoia'],
  'Portimão': ['Portimão', 'Alvor'],
  'Loulé': ['Loulé (São Clemente)', 'Quarteira', 'Almancil'],
  'Almada': ['Almada, Cova da Piedade, Pragal e Cacilhas', 'Costa da Caparica', 'Laranjeiro e Feijó', 'Charneca de Caparica e Sobreda'],
  'Odivelas': ['Odivelas', 'Póvoa de Santo Adrião e Olival Basto', 'Ramada e Caneças'],
  'Loures': ['Loures', 'Santo António dos Cavaleiros e Frielas', 'Sacavém e Prior Velho', 'Moscavide e Portela'],
  'Amadora': ['Águas Livres', 'Alfragide', 'Falagueira-Venda Nova', 'Mina de Água', 'Venteira'],
  'Espinho': ['Espinho', 'Anta e Guetim', 'Paramos'],
  'Maia': ['Cidade da Maia', 'Vila Nova da Telha', 'Pedrouços'],
  'Gondomar': ['Gondomar (São Cosme), Valbom e Jovim', 'Rio Tinto', 'Fânzeres e São Pedro da Cova'],
  'Valongo': ['Valongo', 'Ermesinde', 'Alfena'],
  'Torres Novas': ['Torres Novas (São Pedro)', 'Riachos'],
  'Viseu': ['Viseu (Coração de Jesus)', 'Ranhados', 'Abraveses'],
  'Angra do Heroísmo': ['Sé', 'Conceição', 'São Pedro'],
  'Ponta Delgada': ['São José', 'São Sebastião', 'São Pedro'],
  'Funchal': ['Sé', 'Santa Maria Maior', 'São Martinho', 'Imaculado Coração de Maria'],
  'Oeiras': ['Oeiras e São Julião da Barra, Paço de Arcos e Caxias', 'Algés, Linda-a-Velha e Cruz Quebrada-Dafundo', 'Carnaxide e Queijas', 'Barcarena', 'Porto Salvo'],
  'Vila Franca de Xira': ['Vila Franca de Xira', 'Alverca do Ribatejo e Sobralinho', 'Alhandra, São João dos Montes e Calhandriz', 'Vialonga', 'Castanheira do Ribatejo e Cachoeiras'],
  'Seixal': ['Seixal, Arrentela e Aldeia de Paio Pires', 'Amora', 'Corroios', 'Fernão Ferro'],
  'Sesimbra': ['Sesimbra (Castelo) e Santiago', 'Quinta do Conde', 'Santa Maria do Castelo e São Pedro'],
  'Palmela': ['Palmela', 'Pinhal Novo', 'Poceirão e Marateca', 'Quinta do Anjo'],
  'Santarém': ['Santarém (Marvila)', 'São Salvador', 'Alfange', 'Abrã'],
  'Évora': ['Évora (Sé, São Pedro e Malagueira)', 'Bacelo e Senhora da Saúde', 'Malagueira e Horta das Figueiras'],
  'Beja': ['Beja (Salvador e Santa Maria da Feira)', 'São João Baptista'],
  'Portalegre': ['Sé e São Lourenço', 'São Julião'],
  'Chaves': ['Chaves (Santa Maria Maior)', 'Santa Cruz/Trindade e Sanjurge', 'Madalena'],
  'Bragança': ['Sé, Santa Maria e Meixedo', 'São Tiago'],
  'Castelo Branco': ['Castelo Branco', 'Cebolais de Cima e Retaxo', 'Alcains'],
  'Covilhã': ['Covilhã e Canhoso', 'São Martinho', 'Teixoso e Sarzedo'],
  'Fundão': ['Fundão', 'Alcaria', 'Silvares'],
  'Guarda': ['Guarda (Sé)', 'São Vicente', 'São Miguel da Guarda, Faia, Ramela e Assumada'],
  'Viana do Castelo': ['Viana do Castelo (Santa Maria Maior e Monserrate) e Meadela', 'Areosa', 'Darque'],
  'Peniche': ['Peniche', 'Atouguia da Baleia', 'Ferrel'],
  'Marinha Grande': ['Marinha Grande', 'Vieira de Leiria', 'Moita'],
  'Caldas da Rainha': ['Caldas da Rainha - Nossa Senhora do Pópulo, Coto e São Gregório', 'Nadadouro', 'Salir de Matos'],
  'Elvas': ['Elvas (Assunção, Salvador e Santo Ildefonso)', 'Caia, São Pedro e Alcáçova'],
  'Tomar': ['Tomar (São João Baptista) e Santa Maria dos Olivais', 'Além da Ribeira e Santa Iria'],
  'Ourém': ['Nossa Senhora da Piedade', 'Fátima'],
  'Abrantes': ['Abrantes (São Vicente e São João) e Alferrarede', 'Rossio ao Sul do Tejo'],
  'Estarreja': ['Estarreja', 'Beduído e Veiros', 'Avanca'],
  'Santa Maria da Feira': ['Feira, Travanca, Sanfins e Espargo', 'Lourosa', 'Fiães', 'São João de Ver'],
  'Póvoa de Varzim': ['Póvoa de Varzim, Beiriz e Argivai', 'Aguçadoura e Navais', 'A Ver-o-Mar'],
  'Vila do Conde': ['Vila do Conde', 'Árvore', 'Mindelo', 'Azurara'],
  'Paços de Ferreira': ['Paços de Ferreira', 'Freamunde', 'Frazão'],
  'Penafiel': ['Penafiel', 'Rio de Moinhos', 'Guilhufe e Urrô'],
  'Felgueiras': ['Felgueiras, Margaride (Santa Eulália), Jugueiros e Antas', 'Lagares e Sernande'],
  'Lousada': ['Lousada (São Miguel, Cristelos, Meinedo e Vilar do Torno)', 'Nevogilde e Silvares'],
  'Amarante': ['Amarante (São Gonçalo), Madalena, Cepelos e Gatão', 'Vila Chã do Marão e Ataíde'],
  'Trofa': ['Trofa', 'Bougado (São Martinho e Santiago)', 'Coronado (São Romão e Santiago)'],
  'Baião': ['Baião, Santa Leocádia, Gove e Campelo', 'Ancede e Ribadouro'],
  'Marco de Canaveses': ['Marco e Santa Cruz do Douro', 'Alpendorada, Várzea e Torrão'],
  'Albufeira': ['Albufeira e Olhos de Água', 'Ferreiras', 'Guia', 'Paderne'],
  'Lagos': ['São Sebastião', 'Santa Maria', 'Odiáxere', 'Luz'],
  'Silves': ['Silves', 'Algoz e Tunes', 'Armação de Pêra', 'Pêra'],
  'Tavira': ['Santiago, Santa Maria e Sé', 'Conceição e Cabanas de Tavira'],
  'Olhão': ['Olhão', 'Moncarapacho e Fuseta', 'Quelfes', 'Pechão'],
  'Vila Real de Santo António': ['Vila Real de Santo António', 'Monte Gordo'],
  'Alcobaça': ['Alcobaça e Vestiaria', 'Alfeizerão', 'Nazaré (Pataias e Martingança)'],
  'Óbidos': ['Óbidos (Santa Maria, São Pedro e Sobral da Lagoa)', 'A dos Negros'],
  'Sines': ['Sines', 'Porto Covo'],
  'Grândola': ['Grândola e Santa Margarida da Serra', 'Melides', 'Carvalhal'],
  'Barreiro': ['Barreiro e Lavradio', 'Alto do Seixalinho, Santo André e Verderena', 'Palhais e Coina'],
  'Montijo': ['Montijo e Afonsoeiro', 'Canha', 'Alto Estanqueiro-Jardia'],
  'Moita': ['Moita', 'Alhos Vedros', 'Baixa da Banheira e Vale da Amoreira'],
  'Alcochete': ['Alcochete', 'São Francisco'],
  'Alenquer': ['Alenquer (Santo Estêvão e Triana)', 'Meca'],
  'Torres Vedras': ['São Pedro, Santiago, Santa Maria do Castelo e São Miguel', 'Turcifal'],
  'Mafra': ['Mafra', 'Ericeira', 'Malveira e São Miguel de Alcainça'],
  'Sobral de Monte Agraço': ['Sobral de Monte Agraço', 'Santo Quintino'],
  'Ílhavo': ['Ílhavo (São Salvador)', 'Gafanha da Nazaré', 'Gafanha da Encarnação'],
  'Águeda': ['Águeda e Borralha', 'Aguada de Cima', 'Fermentelos'],
  'Anadia': ['Anadia, Amoreira da Gândara, Arcos e Mogofores', 'Avelãs de Caminho e Vila Nova de Monsarros'],
  'Oliveira de Azeméis': ['Oliveira de Azeméis, Santiago de Riba-Ul, Ul, Macinhata da Seixa e Madail', 'Cucujães'],
  'São João da Madeira': ['São João da Madeira'],
  'Arouca': ['Arouca e Burgo', 'Santa Eulália'],
  'Mealhada': ['Mealhada', 'Luso', 'Pampilhosa'],
  'Figueira da Foz': ['Figueira da Foz e Buarcos', 'Tavarede', 'Lavos'],
  'Cantanhede': ['Cantanhede e Pocariça', 'Ançã', 'Tocha'],
  'Montemor-o-Velho': ['Montemor-o-Velho e Gatões', 'Verride'],
  'Pombal': ['Pombal, Meirinhas e Carnide', 'Vermoil', 'Louriçal'],
  'Ansião': ['Ansião, Avelar e Torre de Vale de Todos', 'Chão de Couce'],
  'Batalha': ['Batalha', 'Reguengo do Fetal'],
  'Porto de Mós': ['Porto de Mós (São João Baptista) e Alqueidão da Serra', 'Mira de Aire'],
};
