export const distritos = [
  'Açores', 'Aveiro', 'Beja', 'Braga', 'Bragança', 'Castelo Branco', 'Coimbra', 'Évora',
  'Faro', 'Guarda', 'Leiria', 'Lisboa', 'Madeira', 'Portalegre', 'Porto', 'Santarém',
  'Setúbal', 'Viana do Castelo', 'Vila Real', 'Viseu',
];

export const concelhosPorDistrito = {
  'Açores': ['Angra do Heroísmo', 'Calheta (São Jorge)', 'Corvo', 'Horta', 'Lagoa', 'Lajes das Flores', 'Lajes do Pico', 'Madalena', 'Nordeste', 'Ponta Delgada', 'Povoação', 'Praia da Vitória', 'Ribeira Grande', 'Santa Cruz da Graciosa', 'Santa Cruz das Flores', 'São Roque do Pico', 'Velas', 'Vila do Porto', 'Vila Franca do Campo'],
  'Aveiro': ['Águeda', 'Albergaria-a-Velha', 'Anadia', 'Arouca', 'Aveiro', 'Castelo de Paiva', 'Espinho', 'Estarreja', 'Santa Maria da Feira', 'Ílhavo', 'Mealhada', 'Murtosa', 'Oliveira de Azeméis', 'Oliveira do Bairro', 'Ovar', 'São João da Madeira', 'Sever do Vouga', 'Vagos', 'Vale de Cambra'],
  'Beja': ['Aljustrel', 'Almodôvar', 'Alvito', 'Barrancos', 'Beja', 'Castro Verde', 'Cuba', 'Ferreira do Alentejo', 'Mértola', 'Moura', 'Odemira', 'Ourique', 'Serpa', 'Vidigueira'],
  'Braga': ['Amares', 'Barcelos', 'Braga', 'Cabeceiras de Basto', 'Celorico de Basto', 'Esposende', 'Fafe', 'Guimarães', 'Póvoa de Lanhoso', 'Terras de Bouro', 'Vieira do Minho', 'Vila Nova de Famalicão', 'Vila Verde', 'Vizela'],
  'Bragança': ['Alfândega da Fé', 'Bragança', 'Carrazeda de Ansiães', 'Freixo de Espada à Cinta', 'Macedo de Cavaleiros', 'Miranda do Douro', 'Mirandela', 'Mogadouro', 'Torre de Moncorvo', 'Vila Flor', 'Vimioso', 'Vinhais'],
  'Castelo Branco': ['Belmonte', 'Castelo Branco', 'Covilhã', 'Fundão', 'Idanha-a-Nova', 'Oleiros', 'Penamacor', 'Proença-a-Nova', 'Sertã', 'Vila de Rei', 'Vila Velha de Ródão'],
  'Coimbra': ['Arganil', 'Cantanhede', 'Coimbra', 'Condeixa-a-Nova', 'Figueira da Foz', 'Góis', 'Lousã', 'Mira', 'Miranda do Corvo', 'Montemor-o-Velho', 'Oliveira do Hospital', 'Pampilhosa da Serra', 'Penacova', 'Penela', 'Soure', 'Tábua', 'Vila Nova de Poiares'],
  'Évora': ['Alandroal', 'Arraiolos', 'Borba', 'Estremoz', 'Évora', 'Montemor-o-Novo', 'Mora', 'Mourão', 'Portel', 'Redondo', 'Reguengos de Monsaraz', 'Vendas Novas', 'Viana do Alentejo', 'Vila Viçosa'],
  'Faro': ['Albufeira', 'Alcoutim', 'Aljezur', 'Castro Marim', 'Faro', 'Lagoa', 'Lagos', 'Loulé', 'Monchique', 'Olhão', 'Portimão', 'São Brás de Alportel', 'Silves', 'Tavira', 'Vila do Bispo', 'Vila Real de Santo António'],
  'Guarda': ['Aguiar da Beira', 'Almeida', 'Celorico da Beira', 'Figueira de Castelo Rodrigo', 'Fornos de Algodres', 'Gouveia', 'Guarda', 'Manteigas', 'Mêda', 'Pinhel', 'Sabugal', 'Seia', 'Trancoso', 'Vila Nova de Foz Côa'],
  'Leiria': ['Alcobaça', 'Alvaiázere', 'Ansião', 'Batalha', 'Bombarral', 'Caldas da Rainha', 'Castanheira de Pêra', 'Figueiró dos Vinhos', 'Leiria', 'Marinha Grande', 'Nazaré', 'Óbidos', 'Pedrógão Grande', 'Peniche', 'Pombal', 'Porto de Mós'],
  'Lisboa': ['Alenquer', 'Amadora', 'Arruda dos Vinhos', 'Azambuja', 'Cadaval', 'Cascais', 'Lisboa', 'Loures', 'Lourinhã', 'Mafra', 'Odivelas', 'Oeiras', 'Sintra', 'Sobral de Monte Agraço', 'Torres Vedras', 'Vila Franca de Xira'],
  'Madeira': ['Calheta (Madeira)', 'Câmara de Lobos', 'Funchal', 'Machico', 'Ponta do Sol', 'Porto Moniz', 'Porto Santo', 'Ribeira Brava', 'Santa Cruz', 'Santana', 'São Vicente'],
  'Portalegre': ['Alter do Chão', 'Arronches', 'Avis', 'Campo Maior', 'Castelo de Vide', 'Crato', 'Elvas', 'Fronteira', 'Gavião', 'Marvão', 'Monforte', 'Nisa', 'Ponte de Sor', 'Portalegre', 'Sousel'],
  'Porto': ['Amarante', 'Baião', 'Felgueiras', 'Gondomar', 'Lousada', 'Maia', 'Marco de Canaveses', 'Matosinhos', 'Paços de Ferreira', 'Paredes', 'Penafiel', 'Porto', 'Póvoa de Varzim', 'Santo Tirso', 'Trofa', 'Valongo', 'Vila do Conde', 'Vila Nova de Gaia'],
  'Santarém': ['Abrantes', 'Alcanena', 'Almeirim', 'Alpiarça', 'Benavente', 'Cartaxo', 'Chamusca', 'Constância', 'Coruche', 'Entroncamento', 'Ferreira do Zêzere', 'Golegã', 'Mação', 'Ourém', 'Rio Maior', 'Salvaterra de Magos', 'Santarém', 'Sardoal', 'Tomar', 'Torres Novas', 'Vila Nova da Barquinha'],
  'Setúbal': ['Alcácer do Sal', 'Alcochete', 'Almada', 'Barreiro', 'Grândola', 'Moita', 'Montijo', 'Palmela', 'Santiago do Cacém', 'Seixal', 'Sesimbra', 'Setúbal', 'Sines'],
  'Viana do Castelo': ['Arcos de Valdevez', 'Caminha', 'Melgaço', 'Monção', 'Paredes de Coura', 'Ponte da Barca', 'Ponte de Lima', 'Valença', 'Viana do Castelo', 'Vila Nova de Cerveira'],
  'Vila Real': ['Alijó', 'Boticas', 'Chaves', 'Mesão Frio', 'Mondim de Basto', 'Montalegre', 'Murça', 'Peso da Régua', 'Ribeira de Pena', 'Sabrosa', 'Santa Marta de Penaguião', 'Valpaços', 'Vila Pouca de Aguiar', 'Vila Real'],
  'Viseu': ['Armamar', 'Carregal do Sal', 'Castro Daire', 'Cinfães', 'Lamego', 'Mangualde', 'Moimenta da Beira', 'Mortágua', 'Nelas', 'Oliveira de Frades', 'Penalva do Castelo', 'Penedono', 'Resende', 'Santa Comba Dão', 'São João da Pesqueira', 'São Pedro do Sul', 'Sátão', 'Sernancelhe', 'Tabuaço', 'Tarouca', 'Tondela', 'Vila Nova de Paiva', 'Viseu', 'Vouzela'],
};

// Nota: cobre os concelhos mais populosos com as freguesias mais conhecidas — não é
// uma lista exaustiva de todas as freguesias de Portugal (seriam milhares de entradas).
// Nos concelhos sem lista própria, a pesquisa fica pelo concelho (nível acima).
export const freguesiasPorConcelho = {
  'Lisboa': [
    'Alvalade', 'Areeiro', 'Arroios', 'Avenidas Novas', 'Belém', 'Benfica',
    'Campo de Ourique', 'Campolide', 'Carnide', 'Estrela', 'Marvila', 'Parque das Nações',
    'Santa Maria Maior', 'Santo António', 'São Domingos de Benfica', 'São Vicente',
  ],
  'Porto': ['Bonfim', 'Campanhã', 'Cedofeita', 'Lordelo do Ouro e Massarelos', 'Paranhos', 'Ramalde'],
  'Cascais': ['Cascais e Estoril', 'Alcabideche', 'Carcavelos e Parede', 'São Domingos de Rana'],
  'Sintra': ['Sintra', 'Queluz e Belas', 'Agualva e Mira-Sintra', 'Rio de Mouro', 'Algueirão-Mem Martins'],
  'Braga': ['São Vicente', 'São José de São Lázaro', 'Maximinos', 'Real'],
  'Faro': ['Faro (Sé e São Pedro)', 'Montenegro'],
  'Coimbra': ['Sé Nova', 'Santo António dos Olivais', 'Santa Clara'],
  'Vila Nova de Gaia': ['Santa Marinha e São Pedro da Afurada', 'Mafamude e Vilar do Paraíso', 'Canidelo'],
  'Setúbal': ['Setúbal (São Julião, Nossa Senhora da Anunciada e Santa Maria da Graça)'],
  'Matosinhos': ['Matosinhos e Leça da Palmeira', 'Perafita, Lavra e Santa Cruz do Bispo'],
  'Guimarães': ['Azurém', 'Creixomil', 'Fermentões', 'Oliveira, São Paio e São Sebastião', 'Urgezes'],
  'Barcelos': ['Barcelos', 'Barcelinhos', 'Arcozelo', 'Abade de Neiva'],
  'Vila Nova de Famalicão': ['Antas e Abade de Vermoim', 'Calendário', 'Gavião', 'Ribeirão'],
  'Aveiro': ['Glória e Vera Cruz', 'São Bernardo', 'Santa Joana', 'Esgueira', 'Cacia'],
  'Leiria': ['Leiria, Pousos, Barreira e Cortes', 'Marrazes e Barosa', 'Parceiros e Azoia'],
  'Portimão': ['Portimão', 'Alvor'],
  'Loulé': ['Loulé (São Clemente)', 'Quarteira', 'Almancil'],
  'Almada': ['Almada, Cova da Piedade, Pragal e Cacilhas', 'Costa da Caparica', 'Laranjeiro e Feijó', 'Charneca de Caparica e Sobreda'],
  'Odivelas': ['Odivelas', 'Póvoa de Santo Adrião e Olival Basto', 'Ramada e Caneças'],
  'Loures': ['Loures', 'Santo António dos Cavaleiros e Frielas', 'Sacavém e Prior Velho', 'Moscavide e Portela'],
  'Amadora': ['Águas Livres', 'Alfragide', 'Falagueira-Venda Nova', 'Mina de Água', 'Venteira'],
  'Espinho': ['Espinho', 'Anta e Guetim', 'Paramos'],
  'Maia': ['Cidade da Maia', 'Vila Nova da Telha', 'Pedrouços'],
  'Gondomar': ['Gondomar (São Cosme), Valbom e Jovim', 'Rio Tinto', 'Fânzeres e São Pedro da Cova'],
  'Valongo': ['Valongo', 'Ermesinde', 'Alfena'],
  'Torres Novas': ['Torres Novas (São Pedro)', 'Riachos'],
  'Viseu': ['Viseu (Coração de Jesus)', 'Ranhados', 'Abraveses'],
  'Angra do Heroísmo': ['Sé', 'Conceição', 'São Pedro'],
  'Ponta Delgada': ['São José', 'São Sebastião', 'São Pedro'],
  'Funchal': ['Sé', 'Santa Maria Maior', 'São Martinho', 'Imaculado Coração de Maria'],
};
